In [1]:
#Importando pacotes
import pandas as pd

In [2]:
txt = open("extrato (12).rtf",newline = '\r').read()

In [3]:
#Formatando as linhas
txt = (txt.split(sep = '\n'))

In [4]:
txt

['------------------------------------------------',
 '                     SICOOB                     ',
 '  SISTEMA DE COOPERATIVAS DE CRÉDITO DO BRASIL  ',
 '    SISBR - SISTEMA DE INFORMÁTICA DO SICOOB    ',
 '                                                ',
 '08/04/2020           EXTRATO            13:00:20',
 '                 CONTA CORRENTE                 ',
 '                                                ',
 'COOP.: 4406-7 / SICOOB CREDICOR/SP              ',
 'CONTA: 2.088-5 / OMENA CORRETORA DE SEGUROS E CO',
 '------------------------------------------------',
 'DATA DOC.   HISTÓRICO                     VALOR ',
 '31/03/2020  SALDO ANTERIOR             9.315,14C',
 '31/03/2020  SALDO BLOQ.ANTERIOR            0,00*',
 '0104 1455628CRÉD.TED-STR                  53,78C',
 '     PORTO SEGURO CIA SEG GERAIS                ',
 '     61.198.164 0001-60                         ',
 '     CODIGO TED: T510082074                     ',
 '0104 1456360CRÉD.TED-STR                  32,59C',
 '     SUL AMERICA SEGUROS DE PESSOAS E PREVIDE   ',
 '     01.704.513 0001-46                         ',
 '     CODIGO TED: T510231742                     ',
 '     TRANSFERENCIA ENTRE CONTAS                 ',
 '0104 1456419CRÉD.TED-STR                 426,03C',
 '     SOMPO SEGUROS S.A.                         ',
 '     61.383.493 0001-80                         ',
 '     CODIGO TED: T510244720                     ',
 '0104 1456741CRÉD.TED-STR                 226,94C',
 '     SUL AMERICA PARTICIPACOES E INVESTIMENTO   ',
 '     32.357.481 0001-83                         ',
 '     CODIGO TED: T510302882                     ',
 '     TRANSFERENCIA ENTRE CONTAS                 ',
 '            SALDO DO DIA =====>       10.054,48C',
 '0204 1457225CRÉD.TED-STR                  77,07C',
 '     PORTO SEGURO CIA SEG GERAIS                ',
 '     61.198.164 0001-60                         ',
 '     CODIGO TED: T510437557                     ',
 '0204 1457466CRÉD.TED-STR                 136,45C',
 '     BRADESCO AUTO RE CIA    SEGUROS            ',
 '     92.682.038 0001-00                         ',
 '     CODIGO TED: T510480056                     ',
 '0204 944723 DÉB.CONV.TELECOMUN.          147,78D',
 '     Internet                                   ',
 '0204 1457973CRÉD.TED-STR                  29,89C',
 '     AZUL COMPANHIA DE SEGUROS GERAIS           ',
 '     33.448.150 0001-11                         ',
 '     CODIGO TED: T510589141                     ',
 '0204 1458251CRÉD.TED-STR                 911,31C',
 '     SUHAI SEGURADORA S A                       ',
 '     16.825.255 0001-23                         ',
 '     CODIGO TED: T510646633                     ',
 '            SALDO DO DIA =====>       11.061,42C',
 '0304 1458500CRÉD.TED-STR                 256,05C',
 '     PORTO SEGURO CIA SEG GERAIS                ',
 '     61.198.164 0001-60                         ',
 '     CODIGO TED: T510730903                     ',
 '0304 1458751CRÉD.TED-STR                 329,85C',
 '     TOKIO MARINE SEGURADORA S A                ',
 '     33.164.021 0001-00                         ',
 '     CODIGO TED: T510774409                     ',
 '            SALDO DO DIA =====>       11.647,32C',
 '0604 1461301CRÉD.TED-STR                 534,28C',
 '     SUL AMERICA PARTICIPACOES E INVESTIMENTO   ',
 '     32.357.481 0001-83                         ',
 '     CODIGO TED: T511377561                     ',
 '     TRANSFERENCIA ENTRE CONTAS                 ',
 '0604 RecargaDEB.RECARGA TEL.              15,00D',
 '0604 1461550CRÉD.TED-STR                 194,67C',
 '     BRADESCO AUTO RE CIA    SEGUROS            ',
 '     92.682.038 0001-00                         ',
 '     CODIGO TED: T511433731                     ',
 '0604 946734 DÉB.CONV.TELECOMUN.           64,99D',
 '     Claro                                      ',
 '0604 946738 DÉB.CONV.TELECOMUN.           66,39D',
 '     Claro                                      ',
 '0604 946739 DÉB.CONV.TELECOMUN.           66,39D',
 '     Claro                                      ',
 '0604 1461638CRÉD.TED-STR                 753,45C',
 '     AZUL COMPANHIA DE SEGUROS GERAIS           ',
 '     33.448.150 0001-11                         ',
 '     CODIGO TED: T511455746                     ',
 '0604 947097 DÉB.TIT.COMPE.EFETI          185,22D',
 '     Verisure                                   ',
 '0604 41  9  APLICAÇÃO RDC              6.000,00D',
 '            SALDO DO DIA =====>        6.731,73C',
 '0704 1462370CRÉD.TED-STR                  55,46C',
 '     PORTO SEGURO CIA SEG GERAIS                ',
 '     61.198.164 0001-60                         ',
 '     CODIGO TED: T511658268                     ',
 '0704 1463378CRÉD.TED-STR                 136,90C',
 '     BRADESCO AUTO RE CIA    SEGUROS            ',
 '     92.682.038 0001-00                         ',
 '     CODIGO TED: T511983704                     ',
 '0704 2079   DEB.PARC.SUBS/INTEG           10,00D',
 '            SALDO DO DIA =====>        6.914,09C',
 '0804 1464463CRÉD.TED-STR                 185,59C',
 '     SUL AMERICA PARTICIPACOES E INVESTIMENTO   ',
 '     32.357.481 0001-83                         ',
 '     CODIGO TED: T512230241                     ',
 '     TRANSFERENCIA ENTRE CONTAS                 ',
 '            SALDO DO DIA =====>        7.099,68C',
 '-------------------- RESUMO --------------------',
 'SALDO EM C.CORRENTE....(+):            7.099,68C',
 'SALDO EM C.INVESTIMENTO(+):                0,00C',
 'LIMITE CONTA GARANTIDA.(+):                0,00C',
 'SALDO DISPONÍVEL.......(=):            7.099,68C',
 'SALDO BLOQ.C.CORRENTE.....:                0,00*',
 'SALDO BLOQ.C.INVESTIMENTO.:                0,00*',
 'VENCTO CONTA GARANTIDA....:                     ',
 'TAXA CONTA GARANTIDA(a.m.):                4,50%',
 'PREVISÃO CPMF.............:                0,00D',
 'PREVISÃO IOF..............:                0,00D',
 'PREVISÃO ENCARGOS.........:                0,00D',
 'PREVISÃO TARIFAS..........:                0,00D',
 '------- SALDO DE APLICAÇÕES EM 07/04/2020-------',
 'RDC - Longo CDI                       36.132,34C',
 '----- 000 EXTRATOS EMITIDOS ATÉ 06/04/2020 -----',
 'OUVIDORIA SICOOB: 08007250996                   ',
 '']

In [5]:
#Separando creditos e de qual seguradoras eles pertencem

creditos = []
seguradoras = []
contador = 0
for i in txt:        
    contador += 1
    if i[len(i)-1:] == 'C' and 'SALDO DO DIA' not in i:
        creditos.append(i)
        seguradoras.append(txt[contador])

In [6]:
seguradoras

['31/03/2020  SALDO BLOQ.ANTERIOR            0,00*',
 '     PORTO SEGURO CIA SEG GERAIS                ',
 '     SUL AMERICA SEGUROS DE PESSOAS E PREVIDE   ',
 '     SOMPO SEGUROS S.A.                         ',
 '     SUL AMERICA PARTICIPACOES E INVESTIMENTO   ',
 '     PORTO SEGURO CIA SEG GERAIS                ',
 '     BRADESCO AUTO RE CIA    SEGUROS            ',
 '     AZUL COMPANHIA DE SEGUROS GERAIS           ',
 '     SUHAI SEGURADORA S A                       ',
 '     PORTO SEGURO CIA SEG GERAIS                ',
 '     TOKIO MARINE SEGURADORA S A                ',
 '     SUL AMERICA PARTICIPACOES E INVESTIMENTO   ',
 '     BRADESCO AUTO RE CIA    SEGUROS            ',
 '     AZUL COMPANHIA DE SEGUROS GERAIS           ',
 '     PORTO SEGURO CIA SEG GERAIS                ',
 '     BRADESCO AUTO RE CIA    SEGUROS            ',
 '     SUL AMERICA PARTICIPACOES E INVESTIMENTO   ',
 'SALDO EM C.INVESTIMENTO(+):                0,00C',
 'LIMITE CONTA GARANTIDA.(+):                0,00C',
 'SALDO DISPONÍVEL.......(=):            7.099,68C',
 'SALDO BLOQ.C.CORRENTE.....:                0,00*',
 '----- 000 EXTRATOS EMITIDOS ATÉ 06/04/2020 -----']

In [7]:
creditos

['31/03/2020  SALDO ANTERIOR             9.315,14C',
 '0104 1455628CRÉD.TED-STR                  53,78C',
 '0104 1456360CRÉD.TED-STR                  32,59C',
 '0104 1456419CRÉD.TED-STR                 426,03C',
 '0104 1456741CRÉD.TED-STR                 226,94C',
 '0204 1457225CRÉD.TED-STR                  77,07C',
 '0204 1457466CRÉD.TED-STR                 136,45C',
 '0204 1457973CRÉD.TED-STR                  29,89C',
 '0204 1458251CRÉD.TED-STR                 911,31C',
 '0304 1458500CRÉD.TED-STR                 256,05C',
 '0304 1458751CRÉD.TED-STR                 329,85C',
 '0604 1461301CRÉD.TED-STR                 534,28C',
 '0604 1461550CRÉD.TED-STR                 194,67C',
 '0604 1461638CRÉD.TED-STR                 753,45C',
 '0704 1462370CRÉD.TED-STR                  55,46C',
 '0704 1463378CRÉD.TED-STR                 136,90C',
 '0804 1464463CRÉD.TED-STR                 185,59C',
 'SALDO EM C.CORRENTE....(+):            7.099,68C',
 'SALDO EM C.INVESTIMENTO(+):                0,00C',
 'LIMITE CONTA GARANTIDA.(+):                0,00C',
 'SALDO DISPONÍVEL.......(=):            7.099,68C',
 'RDC - Longo CDI                       36.132,34C']

In [8]:
#Separando debitos e suas descrições
debitos = []
descricao_deb = []
contador = 0
for i in txt:
    if i[len(i)-1:] == 'D' and 'SALDO DO DIA' not in txt[contador+1]:
        debitos.append(i)
        descricao_deb.append(txt[contador+1])
    if i[len(i)-1:] == 'D' and 'SALDO DO DIA' in txt[contador+1]:
        debitos.append(i)
        descricao_deb.append('     VAZIO')
    contador += 1

In [9]:
txt

['------------------------------------------------',
 '                     SICOOB                     ',
 '  SISTEMA DE COOPERATIVAS DE CRÉDITO DO BRASIL  ',
 '    SISBR - SISTEMA DE INFORMÁTICA DO SICOOB    ',
 '                                                ',
 '08/04/2020           EXTRATO            13:00:20',
 '                 CONTA CORRENTE                 ',
 '                                                ',
 'COOP.: 4406-7 / SICOOB CREDICOR/SP              ',
 'CONTA: 2.088-5 / OMENA CORRETORA DE SEGUROS E CO',
 '------------------------------------------------',
 'DATA DOC.   HISTÓRICO                     VALOR ',
 '31/03/2020  SALDO ANTERIOR             9.315,14C',
 '31/03/2020  SALDO BLOQ.ANTERIOR            0,00*',
 '0104 1455628CRÉD.TED-STR                  53,78C',
 '     PORTO SEGURO CIA SEG GERAIS                ',
 '     61.198.164 0001-60                         ',
 '     CODIGO TED: T510082074                     ',
 '0104 1456360CRÉD.TED-STR                  32,59C',
 '     SUL AMERICA SEGUROS DE PESSOAS E PREVIDE   ',
 '     01.704.513 0001-46                         ',
 '     CODIGO TED: T510231742                     ',
 '     TRANSFERENCIA ENTRE CONTAS                 ',
 '0104 1456419CRÉD.TED-STR                 426,03C',
 '     SOMPO SEGUROS S.A.                         ',
 '     61.383.493 0001-80                         ',
 '     CODIGO TED: T510244720                     ',
 '0104 1456741CRÉD.TED-STR                 226,94C',
 '     SUL AMERICA PARTICIPACOES E INVESTIMENTO   ',
 '     32.357.481 0001-83                         ',
 '     CODIGO TED: T510302882                     ',
 '     TRANSFERENCIA ENTRE CONTAS                 ',
 '            SALDO DO DIA =====>       10.054,48C',
 '0204 1457225CRÉD.TED-STR                  77,07C',
 '     PORTO SEGURO CIA SEG GERAIS                ',
 '     61.198.164 0001-60                         ',
 '     CODIGO TED: T510437557                     ',
 '0204 1457466CRÉD.TED-STR                 136,45C',
 '     BRADESCO AUTO RE CIA    SEGUROS            ',
 '     92.682.038 0001-00                         ',
 '     CODIGO TED: T510480056                     ',
 '0204 944723 DÉB.CONV.TELECOMUN.          147,78D',
 '     Internet                                   ',
 '0204 1457973CRÉD.TED-STR                  29,89C',
 '     AZUL COMPANHIA DE SEGUROS GERAIS           ',
 '     33.448.150 0001-11                         ',
 '     CODIGO TED: T510589141                     ',
 '0204 1458251CRÉD.TED-STR                 911,31C',
 '     SUHAI SEGURADORA S A                       ',
 '     16.825.255 0001-23                         ',
 '     CODIGO TED: T510646633                     ',
 '            SALDO DO DIA =====>       11.061,42C',
 '0304 1458500CRÉD.TED-STR                 256,05C',
 '     PORTO SEGURO CIA SEG GERAIS                ',
 '     61.198.164 0001-60                         ',
 '     CODIGO TED: T510730903                     ',
 '0304 1458751CRÉD.TED-STR                 329,85C',
 '     TOKIO MARINE SEGURADORA S A                ',
 '     33.164.021 0001-00                         ',
 '     CODIGO TED: T510774409                     ',
 '            SALDO DO DIA =====>       11.647,32C',
 '0604 1461301CRÉD.TED-STR                 534,28C',
 '     SUL AMERICA PARTICIPACOES E INVESTIMENTO   ',
 '     32.357.481 0001-83                         ',
 '     CODIGO TED: T511377561                     ',
 '     TRANSFERENCIA ENTRE CONTAS                 ',
 '0604 RecargaDEB.RECARGA TEL.              15,00D',
 '0604 1461550CRÉD.TED-STR                 194,67C',
 '     BRADESCO AUTO RE CIA    SEGUROS            ',
 '     92.682.038 0001-00                         ',
 '     CODIGO TED: T511433731                     ',
 '0604 946734 DÉB.CONV.TELECOMUN.           64,99D',
 '     Claro                                      ',
 '0604 946738 DÉB.CONV.TELECOMUN.           66,39D',
 '     Claro                                      ',
 '0604 946739 DÉB.CONV.TELECOMUN.           66,39D',
 '     Claro                                      ',
 '0604 1461638CRÉD.TED-STR                 753,45C',
 '     AZUL COMPANHIA DE SEGUROS GERAIS           ',
 '     33.448.150 0001-11                         ',
 '     CODIGO TED: T511455746                     ',
 '0604 947097 DÉB.TIT.COMPE.EFETI          185,22D',
 '     Verisure                                   ',
 '0604 41  9  APLICAÇÃO RDC              6.000,00D',
 '            SALDO DO DIA =====>        6.731,73C',
 '0704 1462370CRÉD.TED-STR                  55,46C',
 '     PORTO SEGURO CIA SEG GERAIS                ',
 '     61.198.164 0001-60                         ',
 '     CODIGO TED: T511658268                     ',
 '0704 1463378CRÉD.TED-STR                 136,90C',
 '     BRADESCO AUTO RE CIA    SEGUROS            ',
 '     92.682.038 0001-00                         ',
 '     CODIGO TED: T511983704                     ',
 '0704 2079   DEB.PARC.SUBS/INTEG           10,00D',
 '            SALDO DO DIA =====>        6.914,09C',
 '0804 1464463CRÉD.TED-STR                 185,59C',
 '     SUL AMERICA PARTICIPACOES E INVESTIMENTO   ',
 '     32.357.481 0001-83                         ',
 '     CODIGO TED: T512230241                     ',
 '     TRANSFERENCIA ENTRE CONTAS                 ',
 '            SALDO DO DIA =====>        7.099,68C',
 '-------------------- RESUMO --------------------',
 'SALDO EM C.CORRENTE....(+):            7.099,68C',
 'SALDO EM C.INVESTIMENTO(+):                0,00C',
 'LIMITE CONTA GARANTIDA.(+):                0,00C',
 'SALDO DISPONÍVEL.......(=):            7.099,68C',
 'SALDO BLOQ.C.CORRENTE.....:                0,00*',
 'SALDO BLOQ.C.INVESTIMENTO.:                0,00*',
 'VENCTO CONTA GARANTIDA....:                     ',
 'TAXA CONTA GARANTIDA(a.m.):                4,50%',
 'PREVISÃO CPMF.............:                0,00D',
 'PREVISÃO IOF..............:                0,00D',
 'PREVISÃO ENCARGOS.........:                0,00D',
 'PREVISÃO TARIFAS..........:                0,00D',
 '------- SALDO DE APLICAÇÕES EM 07/04/2020-------',
 'RDC - Longo CDI                       36.132,34C',
 '----- 000 EXTRATOS EMITIDOS ATÉ 06/04/2020 -----',
 'OUVIDORIA SICOOB: 08007250996                   ',
 '']

In [10]:
descricao_deb

['     Internet                                   ',
 '0604 1461550CRÉD.TED-STR                 194,67C',
 '     Claro                                      ',
 '     Claro                                      ',
 '     Claro                                      ',
 '     Verisure                                   ',
 '     VAZIO',
 '     VAZIO',
 'PREVISÃO IOF..............:                0,00D',
 'PREVISÃO ENCARGOS.........:                0,00D',
 'PREVISÃO TARIFAS..........:                0,00D',
 '------- SALDO DE APLICAÇÕES EM 07/04/2020-------']

In [11]:
debitos

['0204 944723 DÉB.CONV.TELECOMUN.          147,78D',
 '0604 RecargaDEB.RECARGA TEL.              15,00D',
 '0604 946734 DÉB.CONV.TELECOMUN.           64,99D',
 '0604 946738 DÉB.CONV.TELECOMUN.           66,39D',
 '0604 946739 DÉB.CONV.TELECOMUN.           66,39D',
 '0604 947097 DÉB.TIT.COMPE.EFETI          185,22D',
 '0604 41  9  APLICAÇÃO RDC              6.000,00D',
 '0704 2079   DEB.PARC.SUBS/INTEG           10,00D',
 'PREVISÃO CPMF.............:                0,00D',
 'PREVISÃO IOF..............:                0,00D',
 'PREVISÃO ENCARGOS.........:                0,00D',
 'PREVISÃO TARIFAS..........:                0,00D']

# Trabalhando créditos

In [12]:
#Agrupando cada crédito com sua respectiva seguradora
cred_e_seg = []
contador = 0
for i in range(len(creditos)):
    cred_e_seg.append(creditos[i] + seguradoras[i])

In [13]:
cred_e_seg

['31/03/2020  SALDO ANTERIOR             9.315,14C31/03/2020  SALDO BLOQ.ANTERIOR            0,00*',
 '0104 1455628CRÉD.TED-STR                  53,78C     PORTO SEGURO CIA SEG GERAIS                ',
 '0104 1456360CRÉD.TED-STR                  32,59C     SUL AMERICA SEGUROS DE PESSOAS E PREVIDE   ',
 '0104 1456419CRÉD.TED-STR                 426,03C     SOMPO SEGUROS S.A.                         ',
 '0104 1456741CRÉD.TED-STR                 226,94C     SUL AMERICA PARTICIPACOES E INVESTIMENTO   ',
 '0204 1457225CRÉD.TED-STR                  77,07C     PORTO SEGURO CIA SEG GERAIS                ',
 '0204 1457466CRÉD.TED-STR                 136,45C     BRADESCO AUTO RE CIA    SEGUROS            ',
 '0204 1457973CRÉD.TED-STR                  29,89C     AZUL COMPANHIA DE SEGUROS GERAIS           ',
 '0204 1458251CRÉD.TED-STR                 911,31C     SUHAI SEGURADORA S A                       ',
 '0304 1458500CRÉD.TED-STR                 256,05C     PORTO SEGURO CIA SEG GERAIS                ',
 '0304 1458751CRÉD.TED-STR                 329,85C     TOKIO MARINE SEGURADORA S A                ',
 '0604 1461301CRÉD.TED-STR                 534,28C     SUL AMERICA PARTICIPACOES E INVESTIMENTO   ',
 '0604 1461550CRÉD.TED-STR                 194,67C     BRADESCO AUTO RE CIA    SEGUROS            ',
 '0604 1461638CRÉD.TED-STR                 753,45C     AZUL COMPANHIA DE SEGUROS GERAIS           ',
 '0704 1462370CRÉD.TED-STR                  55,46C     PORTO SEGURO CIA SEG GERAIS                ',
 '0704 1463378CRÉD.TED-STR                 136,90C     BRADESCO AUTO RE CIA    SEGUROS            ',
 '0804 1464463CRÉD.TED-STR                 185,59C     SUL AMERICA PARTICIPACOES E INVESTIMENTO   ',
 'SALDO EM C.CORRENTE....(+):            7.099,68CSALDO EM C.INVESTIMENTO(+):                0,00C',
 'SALDO EM C.INVESTIMENTO(+):                0,00CLIMITE CONTA GARANTIDA.(+):                0,00C',
 'LIMITE CONTA GARANTIDA.(+):                0,00CSALDO DISPONÍVEL.......(=):            7.099,68C',
 'SALDO DISPONÍVEL.......(=):            7.099,68CSALDO BLOQ.C.CORRENTE.....:                0,00*',
 'RDC - Longo CDI                       36.132,34C----- 000 EXTRATOS EMITIDOS ATÉ 06/04/2020 -----']

In [14]:
#Separando por seguradoras
porto = []
sulamerica = []
mapfre = []
azul=[]
suhai = []
tokio=[]
bradesco = []
liberty = []
hdi = []
ituran =[]
sompo = []
carro_facil = []

for i in cred_e_seg:
    if 'PORTO' in i and 'LOCADORA' not in i:
        porto.append(i)
    if 'PORTO' in i and 'LOCADORA' in i:
        carro_facil.append(i)
    if 'SUL AMERICA' in i:
        sulamerica.append(i)
    if 'MAPFRE' in i:
        mapfre.append(i)
    if 'AZUL' in i:
        azul.append(i)
    if 'SUHAI' in i:
        suhai.append(i)
    if 'TOKIO' in i:
        tokio.append(i)
    if 'BRADESCO' in i:
        bradesco.append(i)
    if 'LIBERTY' in i:
        liberty.append(i)
    if 'HDI' in i:
        hdi.append(i)
    if 'ITURAN' in i:
        ituran.append(i)
    if 'SOMPO' in i:
        sompo.append(i)

In [15]:
#Juntando todos em lista unica
lista_seguradoras = [porto, sulamerica,mapfre,azul,suhai,tokio,bradesco,liberty,hdi,ituran,sompo,carro_facil]

In [16]:
#Separando conteudo de cada transação
listagem = []
for j in lista_seguradoras:
    for i in j:
        listagem.append(i.split(sep = '     '))

In [17]:
listagem

[['0104 1455628CRÉD.TED-STR',
  '',
  '',
  '   53,78C',
  'PORTO SEGURO CIA SEG GERAIS',
  '',
  '',
  ' '],
 ['0204 1457225CRÉD.TED-STR',
  '',
  '',
  '   77,07C',
  'PORTO SEGURO CIA SEG GERAIS',
  '',
  '',
  ' '],
 ['0304 1458500CRÉD.TED-STR',
  '',
  '',
  '  256,05C',
  'PORTO SEGURO CIA SEG GERAIS',
  '',
  '',
  ' '],
 ['0704 1462370CRÉD.TED-STR',
  '',
  '',
  '   55,46C',
  'PORTO SEGURO CIA SEG GERAIS',
  '',
  '',
  ' '],
 ['0104 1456360CRÉD.TED-STR',
  '',
  '',
  '   32,59C',
  'SUL AMERICA SEGUROS DE PESSOAS E PREVIDE   '],
 ['0104 1456741CRÉD.TED-STR',
  '',
  '',
  '  226,94C',
  'SUL AMERICA PARTICIPACOES E INVESTIMENTO   '],
 ['0604 1461301CRÉD.TED-STR',
  '',
  '',
  '  534,28C',
  'SUL AMERICA PARTICIPACOES E INVESTIMENTO   '],
 ['0804 1464463CRÉD.TED-STR',
  '',
  '',
  '  185,59C',
  'SUL AMERICA PARTICIPACOES E INVESTIMENTO   '],
 ['0204 1457973CRÉD.TED-STR',
  '',
  '',
  '   29,89C',
  'AZUL COMPANHIA DE SEGUROS GERAIS',
  '',
  ' '],
 ['0604 1461638CRÉD.TED-STR',
  '',
  '',
  '  753,45C',
  'AZUL COMPANHIA DE SEGUROS GERAIS',
  '',
  ' '],
 ['0204 1458251CRÉD.TED-STR',
  '',
  '',
  '  911,31C',
  'SUHAI SEGURADORA S A',
  '',
  '',
  '',
  '   '],
 ['0304 1458751CRÉD.TED-STR',
  '',
  '',
  '  329,85C',
  'TOKIO MARINE SEGURADORA S A',
  '',
  '',
  ' '],
 ['0204 1457466CRÉD.TED-STR',
  '',
  '',
  '  136,45C',
  'BRADESCO AUTO RE CIA    SEGUROS',
  '',
  '  '],
 ['0604 1461550CRÉD.TED-STR',
  '',
  '',
  '  194,67C',
  'BRADESCO AUTO RE CIA    SEGUROS',
  '',
  '  '],
 ['0704 1463378CRÉD.TED-STR',
  '',
  '',
  '  136,90C',
  'BRADESCO AUTO RE CIA    SEGUROS',
  '',
  '  '],
 ['0104 1456419CRÉD.TED-STR',
  '',
  '',
  '  426,03C',
  'SOMPO SEGUROS S.A.',
  '',
  '',
  '',
  '',
  '']]

In [18]:
#Transformando em DF
df = pd.DataFrame(listagem)

In [19]:
#Criando coluna com a data da transação
for i in range(len(df[0])):
    df[0][i] = (df[0][i][:2])

In [20]:
df

,0,1,2,3,4,5,6,7,8,9
0,01,,,"53,78C",PORTO SEGURO CIA SEG GERAIS,,,,None,None
1,02,,,"77,07C",PORTO SEGURO CIA SEG GERAIS,,,,None,None
2,03,,,"256,05C",PORTO SEGURO CIA SEG GERAIS,,,,None,None
3,07,,,"55,46C",PORTO SEGURO CIA SEG GERAIS,,,,None,None
4,01,,,"32,59C",SUL AMERICA SEGUROS DE PESSOAS E PREVIDE,None,None,None,None,None
5,01,,,"226,94C",SUL AMERICA PARTICIPACOES E INVESTIMENTO,None,None,None,None,None
6,06,,,"534,28C",SUL AMERICA PARTICIPACOES E INVESTIMENTO,None,None,None,None,None
7,08,,,"185,59C",SUL AMERICA PARTICIPACOES E INVESTIMENTO,None,None,None,None,None
8,02,,,"29,89C",AZUL COMPANHIA DE SEGUROS GERAIS,,,None,None,None
9,06,,,"753,45C",AZUL COMPANHIA DE SEGUROS GERAIS,,,None,None,None
10,02,,,"911,31C",SUHAI SEGURADORA S A,,,,,None
11,03,,,"329,85C",TOKIO MARINE SEGURADORA S A,,,,None,None
12,02,,,"136,45C",BRADESCO AUTO RE CIA SEGUROS,,,None,None,None
13,06,,,"194,67C",BRADESCO AUTO RE CIA SEGUROS,,,None,None,None
14,07,,,"136,90C",BRADESCO AUTO RE CIA SEGUROS,,,None,None,None
15,01,,,"426,03C",SOMPO SEGUROS S.A.,,,,,

In [21]:
#Dropando colunas desnecessárias
df.drop(columns = [1,2,5,6,7,8], inplace=True)

In [22]:
df

     0          3                                            4     9
0   01     53,78C                  PORTO SEGURO CIA SEG GERAIS  None
1   02     77,07C                  PORTO SEGURO CIA SEG GERAIS  None
2   03    256,05C                  PORTO SEGURO CIA SEG GERAIS  None
3   07     55,46C                  PORTO SEGURO CIA SEG GERAIS  None
4   01     32,59C  SUL AMERICA SEGUROS DE PESSOAS E PREVIDE     None
5   01    226,94C  SUL AMERICA PARTICIPACOES E INVESTIMENTO     None
6   06    534,28C  SUL AMERICA PARTICIPACOES E INVESTIMENTO     None
7   08    185,59C  SUL AMERICA PARTICIPACOES E INVESTIMENTO     None
8   02     29,89C             AZUL COMPANHIA DE SEGUROS GERAIS  None
9   06    753,45C             AZUL COMPANHIA DE SEGUROS GERAIS  None
10  02    911,31C                         SUHAI SEGURADORA S A  None
11  03    329,85C                  TOKIO MARINE SEGURADORA S A  None
12  02    136,45C              BRADESCO AUTO RE CIA    SEGUROS  None
13  06    194,67C              BRADESCO AUTO RE CIA    SEGUROS  None
14  07    136,90C              BRADESCO AUTO RE CIA    SEGUROS  None
15  01    426,03C                           SOMPO SEGUROS S.A.

In [23]:
for i in range(len(df)):
    df[3][i] = df[3][i].strip('C')

In [24]:
df

     0         3                                            4     9
0   01     53,78                  PORTO SEGURO CIA SEG GERAIS  None
1   02     77,07                  PORTO SEGURO CIA SEG GERAIS  None
2   03    256,05                  PORTO SEGURO CIA SEG GERAIS  None
3   07     55,46                  PORTO SEGURO CIA SEG GERAIS  None
4   01     32,59  SUL AMERICA SEGUROS DE PESSOAS E PREVIDE     None
5   01    226,94  SUL AMERICA PARTICIPACOES E INVESTIMENTO     None
6   06    534,28  SUL AMERICA PARTICIPACOES E INVESTIMENTO     None
7   08    185,59  SUL AMERICA PARTICIPACOES E INVESTIMENTO     None
8   02     29,89             AZUL COMPANHIA DE SEGUROS GERAIS  None
9   06    753,45             AZUL COMPANHIA DE SEGUROS GERAIS  None
10  02    911,31                         SUHAI SEGURADORA S A  None
11  03    329,85                  TOKIO MARINE SEGURADORA S A  None
12  02    136,45              BRADESCO AUTO RE CIA    SEGUROS  None
13  06    194,67              BRADESCO AUTO RE CIA    SEGUROS  None
14  07    136,90              BRADESCO AUTO RE CIA    SEGUROS  None
15  01    426,03                           SOMPO SEGUROS S.A.

In [25]:
df.to_csv('creditos.csv')

# Trabalhando débitos

In [26]:
debitos

['0204 944723 DÉB.CONV.TELECOMUN.          147,78D',
 '0604 RecargaDEB.RECARGA TEL.              15,00D',
 '0604 946734 DÉB.CONV.TELECOMUN.           64,99D',
 '0604 946738 DÉB.CONV.TELECOMUN.           66,39D',
 '0604 946739 DÉB.CONV.TELECOMUN.           66,39D',
 '0604 947097 DÉB.TIT.COMPE.EFETI          185,22D',
 '0604 41  9  APLICAÇÃO RDC              6.000,00D',
 '0704 2079   DEB.PARC.SUBS/INTEG           10,00D',
 'PREVISÃO CPMF.............:                0,00D',
 'PREVISÃO IOF..............:                0,00D',
 'PREVISÃO ENCARGOS.........:                0,00D',
 'PREVISÃO TARIFAS..........:                0,00D']

In [27]:
dia = []

for i in debitos:
    if 'PREVISÃO' in i:
        break
    
    cell = i[0] + i[1]
    
    dia.append(cell)

In [28]:
descricao_lista = []

num = 12
for i in debitos:
    if 'PREVISÃO' in i:
        break
    cell = i[12]+i[13]+i[14]+i[15]+i[16]+i[17]+i[18]+i[19]+i[20]+i[21]+i[22]+i[23]+i[24]+i[25]+i[26]+i[27]+i[28]+i[29]+i[30]
    
    descricao_lista.append(cell)

In [29]:
desc_deb = []

for i in descricao_deb:
    if ('PREVISÃO' in i):
        break
    desc_deb.append(i)

In [30]:
valor = []

for i in debitos:
    if 'PREVISÃO' in i:
        break
    cell = ""
    cell = i[len(i)-9] + i[len(i)-8] + i[len(i)-7] + i[len(i)-6] + i[len(i)-5] + i[len(i)-4] + i[len(i)-3] + i[len(i)-2]
    
    valor.append(cell)

In [31]:
#tira os Debitos duplicados na descricao
desc_deb2 = []

for i in desc_deb:
    if (i.endswith('D')==True):
        i = i[:i.rfind("D")-5]
    desc_deb2.append(i)

In [32]:
debituuu = pd.DataFrame()

In [33]:
debituuu["dia"] = dia
debituuu["descricao"] = descricao_lista
debituuu["descricao2"] = desc_deb2
debituuu["valor"] = valor

In [34]:
debituuu

,dia,descricao,descricao2,valor
0,02,DÉB.CONV.TELECOMUN.,Internet,"147,78"
1,06,DEB.RECARGA TEL.,"0604 1461550CRÉD.TED-STR 194,67C","15,00"
2,06,DÉB.CONV.TELECOMUN.,Claro,"64,99"
3,06,DÉB.CONV.TELECOMUN.,Claro,"66,39"
4,06,DÉB.CONV.TELECOMUN.,Claro,"66,39"
5,06,DÉB.TIT.COMPE.EFETI,Verisure,"185,22"
6,06,APLICAÇÃO RDC,VAZIO,"6.000,00"
7,07,DEB.PARC.SUBS/INTEG,VAZIO,"10,00"

In [35]:
debitos

['0204 944723 DÉB.CONV.TELECOMUN.          147,78D',
 '0604 RecargaDEB.RECARGA TEL.              15,00D',
 '0604 946734 DÉB.CONV.TELECOMUN.           64,99D',
 '0604 946738 DÉB.CONV.TELECOMUN.           66,39D',
 '0604 946739 DÉB.CONV.TELECOMUN.           66,39D',
 '0604 947097 DÉB.TIT.COMPE.EFETI          185,22D',
 '0604 41  9  APLICAÇÃO RDC              6.000,00D',
 '0704 2079   DEB.PARC.SUBS/INTEG           10,00D',
 'PREVISÃO CPMF.............:                0,00D',
 'PREVISÃO IOF..............:                0,00D',
 'PREVISÃO ENCARGOS.........:                0,00D',
 'PREVISÃO TARIFAS..........:                0,00D']

In [36]:
debituuu.to_csv('debitos.csv')

In [37]:
debituuu.valor.sum(axis=0)

'  147,78   15,00   64,99   66,39   66,39  185,226.000,00   10,00'